version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    assignees:
    - tp1de
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "14:30"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
