# Dependabot will run on day 3 of each month at 03:05 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "5 3 3 * *"
    open-pull-requests-limit: 20
    assignees:
      - "tp1de"
    versioning-strategy: "increase"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "5 3 3 * *"
    open-pull-requests-limit: 15
